#ifndef EXECUTE_H
#define EXECUTE_H

void exec_00e0(void);
void exec_00ee(void);
void exec_1nnn(void);
void exec_2nnn(void);
void exec_3xnn(void);
void exec_4xnn(void);
void exec_5xy0(void);
void exec_6xnn(void);
void exec_7xnn(void);
void exec_8xy0(void);
void exec_8xy1(void);
void exec_8xy2(void);
void exec_8xy3(void);
void exec_8xy4(void);
void exec_8xy5(void);
void exec_8xy6(void);
void exec_8xy7(void);
void exec_8xye(void);
void exec_9xy0(void);
void exec_annn(void);
void exec_bnnn(void);
void exec_cxnn(void);
void exec_dxyn(void);
void exec_ex9e(void);
void exec_exa1(void);
void exec_fx07(void);
void exec_fx0a(void);
void exec_fx15(void);
void exec_fx18(void);
void exec_fx1e(void);
void exec_fx29(void);
void exec_fx33(void);
void exec_fx55(void);
void exec_fx65(void);

#endif
